lexik_jwt_authentication:
  secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
  public_key:       '%kernel.project_dir%/config/jwt/public.pem'
  pass_phrase:      'VotrePassphraseIci'    # ou ta passphrase si tu en as mis une
  token_ttl:        3600  # durée de vie du token en secondes