nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin:      ['http://localhost:5174']
    allow_credentials: false   # JWT ne passe pas par cookie
    allow_headers:     ['Content-Type','Authorization']
    allow_methods:     ['GET','POST','PUT','DELETE','OPTIONS']
    max_age:           3600
  paths:
    '^/api/':
      allow_origin:      ['http://localhost:5174']
      allow_credentials: false
      allow_headers:     ['Content-Type','Authorization']
      allow_methods:     ['GET','POST','PUT','DELETE','OPTIONS']