nelmio_cors:
  defaults:
    allow_origin:        ['*']      # ou ['http://localhost:3000'] en prod
    allow_methods:       ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    allow_headers:       ['Content-Type','Authorization']
    expose_headers:      ['Link']
    max_age:             3600
    allow_credentials:   false     # ou true si vous utilisez cookies
  paths:
    '^/api/': ~                   # applique à toutes les routes /api/*