services:
  # par défaut on autowire et autoconfigure tout ; les controllers restent publics
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        false

  # expose tes controllers (si tu as RegistrationController ou SecurityController)
  App\Controller\RegistrationController:
    public: true

  App\Controller\SecurityController:
    public: true

  # LexikJWT fournit déjà ses handlers, pas besoin de les redéclarer si tu n'en as pas de custom